[net9.0] update to Android API 35
We know there will be a few APIs obsolete, as we saw these fail on
dotnet/android's CI:

    src\Compatibility\Core\src\Android\AppCompat\FormsAppCompatActivity.cs(105,4): error CA1422: This call site is reachable on: 'Android' 21.0 and later. 'Window.SetStatusBarColor(Color)' is obsoleted on: 'Android' 35.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)
    src\Compatibility\Core\src\Android\Shapes\ShapeRenderer.cs(483,6): error CA1422: This call site is reachable on: 'Android' 21.0 and later. 'Path.ComputeBounds(RectF, bool)' is obsoleted on: 'Android' 35.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)
    src\Compatibility\Core\src\Android\Shapes\ShapeRenderer.cs(426,6): error CA1422: This call site is reachable on: 'Android' 21.0 and later. 'Path.ComputeBounds(RectF, bool)' is obsoleted on: 'Android' 35.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)